# Generated by Django 3.2.3 on 2021-05-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='false@false.com', max_length=254)),
                ('client_code', models.IntegerField(default=12)),
                ('company_name', models.CharField(default='False', max_length=100)),
                ('mobile_no', models.IntegerField(default=12)),
                ('address', models.TextField(default='failed')),
                ('city', models.CharField(default='failed', max_length=100)),
                ('state', models.CharField(default='failed', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFormAdmin',
            fields=[
                ('tform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tform.tform')),
            ],
            bases=('tform.tform',),
        ),
    ]
