# Generated by Django 3.2.3 on 2021-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tform',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
