# Generated by Django 3.2.3 on 2021-05-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tform', '0002_alter_tform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tform',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='client_code',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='mobile_no',
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
