# Generated by Django 3.2.3 on 2021-05-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tform', '0003_auto_20210529_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tform',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='client_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tform',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
