# Generated by Django 3.2.3 on 2021-05-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tform', '0004_auto_20210529_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
